export const config = {
  WEATHER_API_ENDPOINT: process.env.EXPO_PUBLIC_OPENWEATHER_BASE_URL,
  GEO_API_ENDPOINT: process.env.EXPO_PUBLIC_OPENWEATHER_GEO_URL,
  API_KEY: process.env.EXPO_PUBLIC_OPENWEATHER_API_KEY,
};
