name: Release APK

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Download built APK
        uses: actions/download-artifact@v4
        with:
          name: weatherapp-apk
          path: ./release-apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "WeatherApp Release v1.0.${{ github.run_number }}"
          files: ./release-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
